prototype/gatetrack/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index , name="index"),
    path("project/<int:pk>/", views.project, name="project"),
]

prototype/prototype/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gatetrack.urls')),
]

prototype/gatetrack/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from gatetrack.choices import *

# Create your models here.

#
class Cluster(models.Model):
    name = models.CharField(default="Cluster 10", max_length=50)
    fields = models.TextField(default="D28, Temana")
    remarks = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cluster = models.ForeignKey(Cluster, on_delete=models.CASCADE) #link the user to the cluster
    designation = models.CharField(default="Manager", max_length=100)

    def __str__(self):
        return self.user.username

class Project(models.Model):
    name = models.CharField(default="D28 Phase 1", max_length=50)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    cluster = models.ForeignKey('Cluster', on_delete=models.CASCADE)
    start_date = models.DateTimeField(blank=True, null=True)
    project_type = models.CharField(choices=TYPE_OF_PROJECT, default="Field Development Plan", max_length=100)
    project_info = models.TextField(default="key in your project information over here")
    type_of_scope = models.CharField(choices=SCOPE_OF_WORK, default="Dev/Re-eval/Model", max_length=100)

    def __str__(self):
        return self.name

prototype/gatetrack/views.py
from django.shortcuts import render, get_object_or_404
from .models import Cluster, UserProfile, Project
from django.http import Http404

# Create your views here.

def index(request):
    try:
        clusters = Cluster.objects.all()
    except Cluster.DoesNotExist:
        raise Http404("Error 404")
    return render(request, 'gatetrack/index.html', { 'clusters' : clusters })

def project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    return render(request, 'gatetrack/project.html', {'project' : project})
    

prototype/gatetrack/templates/gatetrack/base.html
{% load static %}

<html>
    <head>
        <title>COE SK OIL GATE TRACKING</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/gatetrack.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet"> 
    </head>
    <body>
        <div class="container">
            <div class="jumbotron">
                <h1><a href="{% url 'index' %}">COE SK OIL PROJECT MANAGEMENT PORTAL</a></h1>
                <p>Gate Tracking and Project Information</p>
            </div>
            {% block body_block %}
            {% endblock %}
        </div>  
    </body>
</html>

prototype/gatetrack/templates/gatetrack/index.html
{% extends 'gatetrack/base.html' %}

{% block body_block %}
    {% for cluster in clusters %}
    <div class="panel panel-default">
        <div class="panel-heading">{{ cluster.name }}</div>
        <div class="panel-body">
            {% for manager in cluster.userprofile_set.all %}
            <span class="label label-default">{{ manager.user.username }}</span>
            {% endfor%}
        </div>
        <div class="panel-body">
            {% for project in cluster.project_set.all %}
                <p><a href="{% url 'project' pk=project.pk %}">{{ project.name }}</a></p>
            {% endfor %}
        </div>  
    </div>
    {% endfor %}    
{% endblock %}

prototype/gatetrack/templates/gatetrack/project.html
{% extends 'gatetrack/base.html' %}

{% block body_block %}
    <div class="panel panel-default">
        <div class="panel-body">
            <h2>{{ project.name }}</h2>
            <p>Project Type: <strong><a href="">{{ project.project_type }}</a></strong>, Scope: {{ project.type_of_scope }}</p>
            <p>{{ project.cluster.name }},<strong> <a href="">Team Lead: {{ project.user.username }}</a></strong></br>Project Commence: {{ project.start_date }}</p>
            <div class="well well-sm"><p><strong>OBJECTIVE</strong></br>{{ project.project_info }}</p></div>
        </div>
    </div>
{% endblock %}